trigger: none

pool: hiteshkapool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
    backendServiceArm: 'hiteshkiservice'
    backendAzureRmStorageAccountName: 'ajaystg1'
    backendAzureRmContainerName: 'ajaycont'